version: "3.8"

services:
  auth-db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - auth-go:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_LOCAL_PORT:-5432}:${POSTGRES_DOCKER_PORT:-5432}"
    # networks:
    #   - auth-go-net
    # healthcheck:
    #   test:
    #     [
    #       "CMD-SHELL",
    #       "pg_isready -U ${POSTGRES_USER:-auth} -d ${POSTGRES_DB:-auth} -h localhost",
    #     ]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5

volumes:
  auth-go:
# networks:
#   auth-go-net:
#     name: auth-go-net
#     external: true
